require("dobe.plugins-setup")
require("dobe.core.options")
require("dobe.core.keymaps")
require("dobe.core.colorscheme")
require("dobe.plugins.comment")
require("dobe.plugins.nvim-tree")
require("dobe.plugins.lualine")
require("dobe.plugins.telescope")
require("dobe.plugins.nvim-cmp")
require("dobe.plugins.lsp.mason")
require("dobe.plugins.lsp.lspsaga")
require("dobe.plugins.lsp.lsptest")

